# Generated by Django 4.2.1 on 2026-01-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tests', through='core.TestQuestion', to='core.question'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test'),
        ),
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test', 'question')},
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='question_text',
        ),
    ]
