# Generated by Django 4.2.1 on 2026-01-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
