# Generated by Django 4.2.1 on 2026-01-08 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_student_user_alter_student_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='imports/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready for Review'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('imported_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('marks', models.IntegerField(default=1)),
                ('question_type', models.CharField(max_length=20)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.importsession')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topic')),
            ],
        ),
    ]
