# Generated by Django 4.2.1 on 2026-01-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studenttestattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='markscheme',
            field=models.TextField(blank=True, help_text='Marking criteria and rubric for AI-assisted evaluation', null=True),
        ),
    ]
